### ISSUE TITLE
同时备份到coding和github出错

### ISSUE THREAD

**Issue by xbotao** [coneycode/hexo-git-backup#14]
我同时备份博客到github和coding，执行`hexo b`， 可以备份到coding，但是不能备份到github

手动备份没有问题
```
fatal: 'github' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by vsxen** [comment]
配置文件？

**Comment by xbotao** [comment]
已经解决，我看了一下。第一次 hexo d 以后，如果增加一个或者修改其中一个的地址出错 我手动完成的

**Comment by xbotao** [comment]
我手动修改.git/config 完成的

**Comment by xbotao** [comment]
我使用的是`npm install hexo-git-back`
在已经备份的情况下，添加一个仓库，再次运行是会出错的，新添加的不能备份。

不知[add remote](https://github.com/coneycode/hexo-git-backup/blob/master/git.js?#L101)是不是每次运行`hexo b`都会进行检验？

另，如果修改已存在的链接也是无效的。

建议[push](https://github.com/coneycode/hexo-git-backup/blob/master/git.js?#L134)之前增加 `git remote set-url --push [name] [newUrl]`

**Comment by coneycode** [comment]
收到，我去看看，多谢。

**Comment by Guxinnn** [comment]
你好 我有同样的问题。 请问能否请教一下如何修改.git/config文件能解决这个问题

**Comment by xbotao** [comment]
`git remote set-url --push [name] [newUrl]  `
用这个指令手动添加
