### ISSUE TITLE
fatal: 'github' does not appear to be a git repository

### ISSUE THREAD

**Issue by marsggbo** [coneycode/hexo-git-backup#16]
```bash
INFO  Start backup: git
[master 36f3d04] Site updated: 2017-03-19 19:21:14
 1 file changed, 1 insertion(+), 1 deletion(-)
fatal: 'github' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
INFO  Backup done: git
```
whats wrong?what should i do?

**Comment by coneycode** [comment]
Please show your git type, github? coding?
and your config.
Thanks.

**Comment by marsggbo** [comment]
- system:**deepin os**
- git type:git
- config:
```yml
backup:
    type: git
    repository:
       github: https://github.com/marsggbo/hexo_source.git,master
```

**Comment by coneycode** [comment]
-git remote add https://github.com/marsggbo/hexo_source.git
-hexo b

**Comment by marsggbo** [comment]
I have tried this way many times,and I just tried again,failed...
![](http://p1.bpimg.com/567571/fa0fd5a22b5377c8.png)

**Comment by coneycode** [comment]
what will be shown when "git -T git@github.com" ?

**Comment by marsggbo** [comment]
@coneycode 
![](http://i1.piimg.com/519918/79c1a76fbc665f70.png)

**Comment by vsxen** [comment]
backup:
    type: git
    repository:
       github: git@github.com:xxx/xxx.git,branchName

这里应该用git  不是https

@coneycode  测试命令是 ssh -T  git@github,com

**Comment by coneycode** [comment]
@vsxen 噗，手误了，不好意思，怎么把ssh写成git了。。
这个换成git就ok了？难道他没开https的通道？

**Comment by vsxen** [comment]
@coneycode 不是开通没开通的  一个repo默认都有两种push的方式，只不过git协议不需要输入用户名密码而已

可以参考https://git-scm.com/book/zh/v1/%E6%9C%8D%E5%8A%A1%E5%99%A8%E4%B8%8A%E7%9A%84-Git-%E5%8D%8F%E8%AE%AE#Git-协议

**Comment by marsggbo** [comment]
原来都是chinese。。。
我试了一下ssh -T git@github.com，下面是结果
```bash
You've successfully authenticated, but GitHub does not provide shell access.

```

**Comment by coneycode** [comment]
@vsxen 哦，我知道你在说什么了。。ssh是公私秘钥的，https是账号密码形式的，估计他之前没配置全局的账号密码。。我还奇怪，一般ssh端口是22.有些默认会关掉。。
@marsggbo 你换成 git@github.com:xxx/xxx.git,branchName 试试应该就ok了。

**Comment by xliez** [comment]
同样的问题哦：
backup:
  type: git
  repository:
    github: git@github.com:xliez/blogBackup.git,master
