### ISSUE TITLE
出现两个WARN

### ISSUE THREAD

**Issue by fengkx** [coneycode/hexo-git-backup#19]
npm install hexo-git-backup --save
npm WARN deprecated swig@1.4.1: This package is no longer maintained
npm WARN deprecated swig@1.4.2: This package is no longer maintained
npm WARN optional dep failed, continuing fsevents@1.1.2
npm WARN optional dep failed, continuing fsevents@1.1.2
 
> hexo-util@0.6.0 postinstall /home/fengkx/node_modules/hexo-git-backup/node_modules/hexo/node_modules/hexo-util
> npm run build:highlight

\
> hexo-util@0.6.0 build:highlight /home/fengkx/node_modules/hexo-git-backup/node_modules/hexo/node_modules/hexo-util
> node scripts/build_highlight_alias.js > highlight_alias.json

 
> dtrace-provider@0.8.3 install /home/fengkx/node_modules/hexo-git-backup/node_modules/hexo/node_modules/hexo-log/node_modules/bunyan/node_modules/dtrace-provider
> node scripts/install.js

hexo-git-backup@0.1.2 node_modules/hexo-git-backup
├── async@0.9.2
├── lodash@2.4.2
├── moment@2.18.1
├── graceful-fs@3.0.11 (natives@1.1.0)
├── swig@1.4.1 (optimist@0.6.1, uglify-js@2.4.24)
└── hexo@3.3.8 (abbrev@1.1.0, pretty-hrtime@1.0.3, hexo-front-matter@0.2.3, archy@1.0.0, titlecase@1.1.2, text-table@0.2.0, deep-assign@2.0.0, tildify@1.2.0, strip-indent@1.0.1, bluebird@3.5.0, hexo-i18n@0.2.1, moment-timezone@0.5.13, chalk@1.1.3, minimatch@3.0.4, swig-extras@0.0.1, js-yaml@3.9.0, moment@2.13.0, hexo-util@0.6.0, hexo-cli@1.0.3, hexo-log@0.1.3, hexo-fs@0.2.1, nunjucks@2.5.2, lodash@4.17.4, warehouse@2.2.0, swig@1.4.2, cheerio@0.20.0)

**Comment by vsxen** [comment]
warn可以不用在意  或者升级swig和fsevents（可能会出现问题）

**Comment by coneycode** [comment]
swig@1.4.2 是因为这个库不更新了，暂时请忽略掉，我近期会更新版本库
