### ISSUE TITLE
 does not appear to be a git repository

### ISSUE THREAD

**Issue by zhuxingsheng** [coneycode/hexo-git-backup#26]
backup:
	type: git
	repo:
		gitee: git@gitee.com:jjkjachcu/hexo.git,master

`$ hexo b
(node:9124) [DEP0061] DeprecationWarning: fs.SyncWriteStream is deprecated.
INFO  Start backup: git
[master d609c34] Site updated: 2018-11-22 15:12:24
 1 file changed, 1 deletion(-)
fatal: 'gitee' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
INFO  Backup done: git`

$ git push origin master
Counting objects: 5, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 305 bytes | 0 bytes/s, done.
Total 3 (delta 2), reused 0 (delta 0)
remote: Powered by Gitee.com
To git@gitee.com:jjkjachcu/hexo.git
   447e5bc..d609c34  master -> master

使用hexo b不能正常push，只能手动push才成功

**Comment by coneycode** [comment]
收到，看上去是gitee识别问题，我去看看代码。

**Comment by zhuxingsheng** [comment]
从以前的issue找到了解决方法

方法1：
执行如下命令
git remote add github git@github.com:xxx/xxx.git
hexo b

方法2:
删除本地目录下的 .git 目录
然后执行命令
hexo b
直到看到如下输出：

[new branch] master -> master
Branch master set up to track remote branch master from github.
INFO Backup done: git

end

**Comment by coneycode** [comment]
好的，我去看看代码上有什么问题吧...
