### ISSUE TITLE
推送到Github 报错及解决

### ISSUE THREAD

**Issue by simon7073** [coneycode/hexo-git-backup#40]
## 错误

我的配置是这样的
> backup:
  &ensp;&ensp; type: git
  &ensp;&ensp; repository:
  &ensp;&ensp;&ensp;&ensp; github: git@github.com:nsleep/nsleep.github.io.git,backup

我在执行`hexo b`后，控制台显示

> INFO  Start backup: git
[backup 0431bed] Site updated: 2020-02-29 21:16:51
 1 file changed, 1 insertion(+), 1 deletion(-)
fatal: 'github' does not appear to be a git repository
fatal: Could not read from remote repository.
> Please make sure you have the correct access rights
and the repository exists.
INFO  Backup done: git

我在`node_modules/hexo-git-backup/git.js` 文件中加入一行以显示执行的命令 <del> （行77）</del>
![image](https://user-images.githubusercontent.com/23132161/75618598-af7d9680-5bab-11ea-8f18-55886677e9a2.png)

出现以下提示
> nothing to commit, working tree clean
git [ 'push', '-u', 'github', 'master:backup', '--force' ]
fatal: 'github' does not appear to be a git repository
fatal: Could not read from remote repository.

以此可见错误原因。

---

## 解决

然后自己YY了一个解决方案——
将这一行<del>（行135）</del>
> commands.push(['push', '-u', t, 'master:' + repo[t].branch, '--force']);
改成
> commands.push(['push', '-u', t, 'backup:' + repo[t].branch, '--force']);

配置文件中`github` 更改为`origin`

> INFO  Start backup: git
git [ 'add', '-A' ]
git [ 'commit', '-m', 'Site updated: 2020-03-01 11:11:38' ]
[backup 3878af7] Site updated: 2020-03-01 11:11:38
&ensp;1 file changed, 2 insertions(+), 1 deletion(-)
git [ 'push', '-u', 'origin', 'backup:backup', '--force' ]
Branch 'backup' set up to track remote branch 'backup' from 'origin'.
To https://github.com/nsleep/nsleep.github.io
 &ensp;&ensp;dd809ad..3878af7  backup -> backup
INFO  Backup done: git

问题解决！

**Comment by andyyxw** [comment]
@nsleep 我的coding和gitee推送不了backup，也是类似的报错，deploy都是正常的。请问是啥原因呢
<img width="599" alt="Snipaste_2020-04-26_11-25-33" src="https://user-images.githubusercontent.com/41931722/80296996-e1793680-87b1-11ea-8d14-1d94d23e2e19.png">

**Comment by shaojunying** [comment]
强 同样的问题 解决了

**Comment by greenhandzdl** [comment]
error: src refspec backup does not match any
error: failed to push some refs to 'git@github.com:greenhandzdl/hexo.bak.git'

**Comment by greenhandzdl** [comment]
啊，感谢，在135行更改那里多打了个空格后面就开始报上面的那个错误，还有，记得`git push`
