### ISSUE TITLE
运行hexo backup出错

### ISSUE THREAD

**Issue by zhangleijuly** [coneycode/hexo-git-backup#7]
配置写
backup:
    type: git
    theme: tranquilpeak
    repository:
        github: git@github.com:XXX/XXX.git,master
提示
fatal: 'github' does not appear to be a git repository
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
配置写
backup:
    type: git
    theme: tranquilpeak
    repository:
        gitcafe: git@github.com:XXX/XXX.git,master
提示
fatal: 'gitcafe' does not appear to be a git repository
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
是不是github/gitcafe这个关键字的处理出问题了

**Comment by coneycode** [comment]
加上缩进试试呢？
backup:
    type: git
    theme: tranquilpeak
    repository:
         gitcafe: git@github.com:XXX/XXX.git,master

**Comment by coneycode** [comment]
你这个是因为没有找到github or gitcafe上的项目吧？

**Comment by zhangleijuly** [comment]
但是项目是有的，不知道是什么原因找不到呢

**Comment by coneycode** [comment]
这个应该是你的项目没有配置好，这个错误表示连接不到远程git，你在本地
ssh -T git@github.com试试呢？

**Comment by gdky005** [comment]
1.ssh -T git@github.com:

Hi gdky005! You've successfully authenticated, but GitHub does not provide shell access.

2._config.yml

backup:
    type: git
    repository:
       github: git@github.com:XXX.git,backup

3.分支 确定存在

3.hexo -b :

INFO  Start backup: git
On branch backup
Your branch is up-to-date with 'origin/backup'.
nothing to commit, working directory clean
fatal: 'github' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
INFO  Backup done: git

**Comment by zhangleijuly** [comment]
这个指令是可以连接的，另一个issue和我遇到的问题应该是同一个

**Comment by coneycode** [comment]
抱歉，最近比较忙，反馈不够及时，我这两天看看。

**Comment by gdky005** [comment]
只回复妹子的，。。。

**Comment by vssli** [comment]
I got the same problem.
Cannot find the respository.
Do you people fix this problem?

**Comment by coneycode** [comment]
有人帮忙解答了这个问题。
我最近比较忙，稍后会fix掉这个bug。目前可以先这么解决。


方法1：
执行如下命令
git remote add github git@github.com:xxx/xxx.git
hexo b

方法2:
删除本地目录下的 .git 目录
然后执行命令
hexo b
直到看到如下输出：

[new branch] master -> master
Branch master set up to track remote branch master from github.
INFO Backup done: git

end

---

**Comment by gdky005** [comment]
N 天后，又回到这里了， 楼上的答案确实解决了问题。
