### ISSUE TITLE
fatal: 'github' does not appear to be a git repository

### ISSUE THREAD

**Issue by gdky005** [coneycode/hexo-git-backup#8]
1.ssh -T git@github.com:

Hi gdky005! You've successfully authenticated, but GitHub does not provide shell access.

2._config.yml

backup:
type: git
repository:
github: git@github.com:XXX.git,backup

3.分支 确定存在

3.hexo -b :

INFO Start backup: git
On branch backup
Your branch is up-to-date with 'origin/backup'.
nothing to commit, working directory clean
fatal: 'github' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
INFO Backup done: git

**Comment by coneycode** [comment]
额。我也来回复下你。。。最近各种深圳哈尔滨上海的来回跑。。。fix有点慢。。

**Comment by LiZhenNet** [comment]
我也是同样的问题，之前在一台电脑上backup成功了，换了台电脑后backup失败了

`fatal: 'github' does not appear to be a git repository
fatal: Could not read from remote repository.`

**Comment by ReeFish** [comment]
fatal: 'github' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

出现上面的提示，说明github远端仓库和本地仓库的关联关系没有建立
可以尝试两种方法解决：
方法1：
执行如下命令
git remote add github git@github.com:xxx/xxx.git
hexo b

方法2:
删除本地目录下的 .git 目录
然后执行命令
hexo b
直到看到如下输出：
 * [new branch]      master -> master
Branch master set up to track remote branch master from github.
INFO  Backup done: git

才可以关闭命令终端

**Comment by ReeFish** [comment]
@LiZhenNet

换其他电脑的话，clone的时候要注意，需要带-o参数来指定远端主机名称（比如，你配置的是github）
git clone -o github git@github.com:xxx/xxx.git

**Comment by LiZhenNet** [comment]
@ReeFish  3Q~

**Comment by sxgc** [comment]
$ hexo b
INFO  Start backup: git
[master 3fa339c] Site updated: 2016-03-12 12:17:20
 1 file changed, 2 insertions(+), 2 deletions(-)
Branch master set up to track remote branch Hexo from github.
To git@github.com:sxgc/Hexo.git
   0e6620b..3fa339c  master -> Hexo
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
INFO  Backup done: git

请问这个怎么解决

**Comment by gdky005** [comment]
这个问题和  #7 问题是一样的。解决方法如下：

方法1：
执行如下命令
git remote add github git@github.com:xxx/xxx.git
hexo b

方法2:
删除本地目录下的 .git 目录
然后执行命令
hexo b
直到看到如下输出：

[new branch] master -> master
Branch master set up to track remote branch master from github.
INFO Backup done: git

end

N 个月后又回到这个问题上了，不过已经解决了，群主可以 fix 这两个问题了。
