### ISSUE TITLE
我本地分支不是master，备份的时候还是用的master分支？

### ISSUE THREAD

**Issue by ge-ce** [coneycode/hexo-git-backup#9]

**Comment by coneycode** [comment]
不是。你看readme，可以设置branchName。

**Comment by ge-ce** [comment]
不是啊，readme的branchName 是提交到的远程分支，是 本地master → 远程branchName，我要的是本地不是master

**Comment by ge-ce** [comment]
我本地由于由于某些原因用 `git checkout name` 切换到了新的分支。。

**Comment by ge-ce** [comment]
再描述清楚点，假设我本地有 master 和 test 分支，远程也是 master 和 test 分支，在  _config.yml 中设置了 branchName 为 test，那么 hexo b 是将本地 master 提交到了远程 test，但是我本地切换到 test 分支工作，hexo b 仍然提交本地 master 到远程 test 。

**Comment by coneycode** [comment]
懂了。本地没处理多分支。只能是master。-_-！

**Comment by coneycode** [comment]
后面更新版本后通知你。
